name: Feature Request
description: Source & Concept Vocabularies Feature Request
title: "[New Feature]: "
labels: ["enhancement"]
assignees:
  - wieandk
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using the SSDQA ecosystem! Please complete this form to submit a feature request for the Source & Concept Vocabularies module.
  - type: checkboxes
    attributes:
      label: Function
      description: Which function would benefit from this new feature?
      options:
        - label: scv_process
        - label: scv_output
  - type: dropdown
    attributes:
      label: Function Configuration
      description: Does this feature apply to a specific function configuration? Multiple selections are allowed if needed.
      multiple: true
      options:
        - "Single Site, Exploratory, Cross-Sectional"
        - "Single Site, Anomaly Detection, Cross-Sectional"
        - "Single Site, Exploratory, Longitudinal"
        - "Single Site, Anomaly Detection, Longitudinal"
        - "Multi-Site, Exploratory, Cross-Sectional"
        - "Multi-Site, Anomaly Detection, Cross-Sectional"
        - "Multi-Site, Exploratory, Longitudinal"
        - "Multi-Site, Anomaly Detection, Longitudinal"
  - type: textarea
    attributes:
      label: Feature Description
      description: Please describe the feature you would like to request.
  - type: textarea
    attributes:
      label: Supporting Materials
      description: Please include any supporting materials (i.e. code snippets, documentation) that you would like to include with your request.
